name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Restore PostgreSQL database
        run: |
          service postgresql start && psql -U postgres -d lessons -h localhost -p 5432 -f homework_8/integration_tests/backups/backup.sql

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run unit tests
        run: cd homework_8/unit_tests && go test -v ./...

      - name: Run integration tests
        run: cd homework_8/integration_tests && go test -v ./...